
# Part 1. Samuli's IODS adventure!

*[Link to my repository](https://github.com/sampotarmo/IODS-project)

```{r}
date()
```

I'm glad I didn't do this course on my work computer. At first there was a quite much to download, intall and update.

I've been using R sporadically. I learn a bit, use it for a while and then forget the whole thing. And once again I have to start from zero. The most difficult thing with R for me has been the data wrangling. So I'm quite excited for the possibility to finally tackle this problem!

Few useful links
* 1. [Markdown basics](https://rmarkdown.rstudio.com/lesson-1.html)
* 2. [R Community](https://www.r-statistics.com/tag/r-community/)
* 3. [Rpubs](https://rpubs.com/)

Apparently, as seen above, you can not put links to lists. At least not in a normal way:

`* list 1` \
`* list 2` \
`* list 3`

..which should end up as:

* list 1
* list 2
* list 3

By now there's some questions I'd like to get an answer. And if you, my dear reader, know the answer, please share! First and foremost, is there some way to "surf" the data? Now there's a bunch of variables but I don't have a clue what they contain. Sure, there's the data dictionary provided on the course page. But I'd rather have labels for variables.